name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer
        pip install cython==0.29.33
        
    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        echo "### Android Licenses ###" > ~/.android/licenses/android-sdk-license
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> ~/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> ~/.android/licenses/android-sdk-license
        
    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: video-downloader-apk
        path: bin/*.apk
        retention-days: 30
