name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          unzip \
          zip \
          wget \
          libncurses6 \
          libstdc++6 \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Install Android SDK (manually)
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d android-sdk
        mkdir -p android-sdk/cmdline-tools/latest
        mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/ || true

        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/.buildozer/android/platform/android-sdk

    - name: Build APK
      run: |
        export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
        export ANDROIDNDK="$ANDROIDSDK/ndk-bundle"
        export PATH="$ANDROIDSDK/platform-tools:$PATH"
        buildozer -v android debug
        ls -la bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: video-downloader-apk
        path: bin/*.apk
        retention-days: 30
